# lazygit-config.yml
gui:
  showIcons: true
  sidePanelWidth: 0.2
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
os:
  edit: 'nvim {{filename}}'
  editAtLine: 'nvim --line={{line}} {{filename}}'
  editAtLineAndWait: 'nvim --block --line={{line}} {{filename}}'
  editInTerminal: true
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
