# lazygit-config.yml
gui:
  showIcons: true
  sidePanelWidth: 0.2
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
os:
  editCommand: 'nvim'
  editCommandTemplate: '{{editor}} +{{line}} {{filename}}'
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
