command_timeout = 200

[cmd_duration]
  disabled = true

[aws]
disabled = false

[directory]
truncation_length = 10

[docker_context]
disabled = false


[git_metrics]
disabled = false

[package]

[terraform]
format = '[$symbol$version]($style) '

[localip]
disabled = false
