return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "angular-language-server",
      "bash-language-server",
      "css-lsp",
      "dockerfile-language-server",
      "eslint-lsp",
      "gopls",
      "gradle-language-server",
      "html-lsp",
      "json-lsp",
      "jdtls",
      "lua-language-server",
      "marksman",
      "nginx-language-server",
      "prettierd",
      "rubocop",
      "shellcheck",
      "shfmt",
      "solargraph",
      "sql-formatter",
      "stylua",
      "terraform-ls",
      "tflint",
      "typescript-language-server",
      "yaml-language-server",
    },
  },
}
